from app.domain.interfaces import GroqLLMClient
from app.domain.entities import TrafficPattern, RepoAnalysis, LoadTestScript, Dataset
from groq import Groq
import os
import json

class GroqLLMClientImpl(GroqLLMClient):
    def __init__(self, api_key: str = None):
        if not api_key:
            api_key = os.getenv("GROQ_API_KEY")
        self.client = Groq(api_key=api_key)

    def analyze_and_generate(self, traffic: TrafficPattern, repo_analysis: RepoAnalysis, target_endpoint: str) -> tuple[LoadTestScript, Dataset]:
        if not self.client.api_key:
             return LoadTestScript(script_content="// No Groq API Key provided\n import http from 'k6/http';\n export default function() { http.get('http://test.k6.io'); }"), Dataset(csv_content="col1,col2\nval1,val2")
        
        dataset_filename = "data.csv"
        prompt = f"""
        You are a strict k6 script generator. You MUST generate a valid JSON object with exactly two keys: "k6_script" (string) and "csv_data" (string).
        
        CRITICAL RULES FOR "csv_data":
        - It MUST be a single string containing comma-separated values (CSV format). Do NOT output a JSON object or array for this key.
        - The CSV MUST contain exactly 10 rows of mock test data parameters. It CANNOT be empty.
        - READ THE REPO ANALYSIS CONTEXT: Analyze the target endpoint's expected payload, query parameters, or path variables.
        - The CSV columns MUST literally represent those required fields. Do NOT use fake dummy schemas like "user_id,request_metadata" unless the target API specifically expects it.
        - YOU MUST USE EXPLICIT `\\n` NEWLINE CHARACTERS TO SEPARATE EACH ROW IN THE STRING. Do not just chain all values together with commas.
        
        CRITICAL RULES FOR "k6_script":
        1. UNDER NO CIRCUMSTANCES vary from using the `constant-arrival-rate` executor. Provide the exact options block:
           `export const options = {{ scenarios: {{ load_test: {{ executor: 'constant-arrival-rate', rate: {traffic.rps}, timeUnit: '1s', duration: '5m', preAllocatedVUs: 50, maxVUs: 1000 }} }} }};`
        2. DO NOT USE THE `sleep()` FUNCTION ANYWHERE IN THE SCRIPT. If you use `sleep(`, the response is invalid.
        3. MANDATORY URL: Your script function MUST submit {traffic.http_method} requests to exactly this URL: `{target_endpoint}`
        4. Integrate `SharedArray` from `k6/data` to load the `{dataset_filename}` dataset.
        
        Traffic Pattern Analysis (incorporate into script):
        - Required Target RPS: {traffic.rps}
        - P95 Latency Threshold: {traffic.p95_latency_ms}ms (add to options thresholds)
        - Error Rate Threshold: {traffic.error_rate} (add to options thresholds)
        - Payload Size: {traffic.payload_size_bytes} bytes
        - Target HTTP Method: {traffic.http_method}
        
        Repo Analysis Context (use for endpoint/logic):
        {repo_analysis.endpoint_logic_summary}
        """
        
        try:
            completion = self.client.chat.completions.create(
                messages=[
                    {
                        "role": "system",
                        "content": "You output ONLY raw valid JSON matching the user's keys. Never include markdown formatting or explanations."
                    },
                    {
                        "role": "user",
                        "content": prompt,
                    }
                ],
                model="llama-3.3-70b-versatile",
                response_format={"type": "json_object"},
            )
            
            response_content = completion.choices[0].message.content
            data = json.loads(response_content)
            
            k6_script = data.get("k6_script", "// Error generating script")
            csv_data = data.get("csv_data", "col1,col2\nval1,val2")
            
            if isinstance(csv_data, str):
                # Replace literal slash-n strings generated by LLM with actual newlines
                csv_data = csv_data.replace('\\n', '\n')
            
            if not isinstance(csv_data, str):
                # LLM incorrectly returned JSON instead of CSV string, serialize it to string
                csv_data = json.dumps(csv_data)

            return LoadTestScript(script_content=k6_script), Dataset(csv_content=csv_data)

        except Exception as e:
            return LoadTestScript(script_content=f"// Error communicating with Groq: {str(e)}"), Dataset(csv_content="error\ntrue")
