---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.myrepo.dev
  resources:
  - ephemeralenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.myrepo.dev
  resources:
  - ephemeralenvs/finalizers
  verbs:
  - update
- apiGroups:
  - apps.myrepo.dev
  resources:
  - ephemeralenvs/status
  verbs:
  - get
  - patch
  - update
